# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
matrix:
  include:
    - python: 3.3
      env: USE_CHROOT=1 ARCH=i386 DIST=trusty PYTHON=3.4
      sudo: true
      addons:
        apt:
          packages:
            - *common_packages
            - debootstrap
    - python: 3.2
      env: USE_DEBUG=1
      addons:
        apt:
          packages:
            - *common_packages
            - python3-dbg
            - python3-dev
            - python3-nose
    - python: 2.7
      env: NPY_RELAXED_STRIDES_CHECKING=0 PYTHON_OO=1
    - python: 2.7
      env: USE_WHEEL=1
    - python: 2.7
      env: PYTHONOPTIMIZE=2
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Build into own virtualenv
  # We therefore control our own environment, avoid travis' numpy
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -V
  - pip install --upgrade pip setuptools
  - pip install nose
  # pip install coverage
  # Speed up install by not compiling Cython
  - pip install --install-option="--no-cython-compile" Cython
  - popd

script:
  - ./tools/travis-test.sh
